### ISSUE TITLE
RDFizer: MARC Auth record sample file

### ISSUE THREAD

**Issue by idoiamurua** [ALIADA/aliada-tool#107]
Could anyone send to me one or several MARCXMOL authority records that generate triples in the RDFizer?

Elena has already sent to me two, but they do not generate any triples.

**Comment by agazzarini** [comment]
Hi Idoia, within the RDFizer project, under src/test/resources there are 
several files (If I remember, we have 2 samples for authority)

**Comment by idoiamurua** [comment]
I have just imported and RDFized the two samples for authority under the RDFizer project, but it does not generate any triples either.
There are no error logs any where. The "total_triples_produces" filed in the `aliada`.`rdfizer_job_stats` table is 0.

**Comment by agazzarini** [comment]
Did you create what described in the configuration section? you need

- a new entry on the configuration file
- a new data dir
- the user interface must create a row in the database with all input 
data specifying "auth" as format because yes, it is marcxml but the 
management is different

As a shortcut you can

a) create a row on the database with, let's say, id 1 and format "auth". 
On the datafile column put somethign like "/tmp/aut-rec.xml"
b) put the file under /tmp and call it aut-rec.xml
c) start the rdfizer
d) open a shell and type

curl -X PUT "http://127.0.0.1:8891/rdfizer/jobs/1"

That will starts the RDFizer process for that file, bypassing the user 
interface

Best
Andrea

**Comment by agazzarini** [comment]
I'm closing the issue as I tried as described above and the triples are corrected printed out

(If you want to avoid the connection to Virtuoso, open the "pipeline-definition.xml", go to the end of the file and replace the "add-2-rff-store" with one of the following:

- debugger: a processor that just prints out the outcoming triples
- no-op: a processor that does nothing (the triple are still produced but you don't see them)

**Comment by idoiamurua** [comment]
You mentioned that the following should be done:

* a new entry on the configuration file: Do you mean "auth.input.dir=/work/data/aliada/auth" in "default-pipeline-settings.properties" file? It is already there.
* a new data dir: Do I have to create "/work/data/aliada/auth" folder? It is already created. 
* the user interface must create a row in the database with all input
data specifying "auth" as format because yes, it is marcxml but the
management is different. The file is imported correctly by the UI. The corresponding rows for the Profile/Template are already created in the DB.

**Comment by agazzarini** [comment]
Ok, for the last point: I meant a row for that specific job in
rdfizer_job_instances with "auth" as value in the format column

2015-05-12 10:15 GMT+02:00 Idoia <notifications@github.com>:

**Comment by idoiamurua** [comment]
OK. That is the problem then! 
@xmolero The column "format" in "rdfizer_job_instances" table says now "marcxml" instead of "auth" when importing a MARCXML Authorities file.

**Comment by agazzarini** [comment]
For each format there's a given value: marcxml, lido, auth, dc

2015-05-12 10:27 GMT+02:00 Idoia <notifications@github.com>:

**Comment by idoiamurua** [comment]
I am going to correct the following in "auth.frbr.n3.vm" file:

```
#set($F10_Person = "#ecrm('F10_Person')")
```
should be:
```
#set($F10_Person = "#efrbroo('F10_Person')")
```

And:
```
#mapping_with_repeatable_tag_three_entities($xpath.dfs("368","d",$root) $person_s "F13_Identifier" "E90_Symbolic_Object" "#ecrm('F13_Identifier')" "#ecrm('E90_Symbolic_Object')" "#ecrm('P1_is_identified_by')" "#ecrm('R8_consists_of')")
```
should be:
```
#mapping_with_repeatable_tag_three_entities($xpath.dfs("368","d",$root) $person_s "F13_Identifier" "E90_Symbolic_Object" "#efrbroo('F13_Identifier')" "#ecrm('E90_Symbolic_Object')" "#ecrm('P1_is_identified_by')" "#ecrm('R8_consists_of')")
```

When the entity name starts with E use  `#ecrm` prefix, and if it starts with F use  `#efrbroo` prefix.

**Comment by eturienzo** [comment]
Ok, the auth format was added to the database
