### ISSUE TITLE
UI: Change the hard coded REST domain names

### ISSUE THREAD

**Issue by idoiamurua** [ALIADA/aliada-tool#114]
@xmolero 
When installing the second version of aliada-tool at MFAB I have realised that the domian name in the REST URL-s is hardcoded as "http://aliada:8080/....". Because of this, It gives errors at MFAB when the UI invokes the RDFizer.
It seems in the fisrt version of aliada-tool it was hard coded as "http://localhost:8080/...", and it worked OK in MFAB.

**Comment by eturienzo** [comment]
I have done the change on ConversionAction, LinkingAction and PublishAction to invoke http://localhost:8080...

**Comment by idoiamurua** [comment]
The errors I had in MFAB where not related to the "http://aliada:8080/...." hard coded string. I have just realised that it was realted to the JDK version used by Tomcat. The RDFiser needs JDK 1.8 but Tomcat was running with JDK 1.7. I have just fixed that.

**Comment by xmolero** [comment]
Fixed and commit.
