### ISSUE TITLE
Template entities translation

### ISSUE THREAD

**Issue by xmolero** [ALIADA/aliada-tool#124]
Hi Andrea,
 
I need the following translations to Italian:
-	Work
-	Expression
-	Manifestation
-	Item
-	Person
-	Corporate Body
-	Concept
-	Object
-	Event
-	Place
-	Family
-	Dimension
-	Rights
 
Thank you!

**Comment by agazzarini** [comment]
@xmolero here it is:

Work=Opera
Expression=Espressione
Manifestation=Manifestazione
Item=Item (it is latin, not english so should be Item in any language)
Person=Persona
Corporate Body=Ente
Concept=Soggetto
Object=Oggetto
Event=Evento
Place=Luogo
Family=Famiglia
Dimension=Dimensione
Rights=Diritti
