### ISSUE TITLE
User - interface: user log for mandatory tags

### ISSUE THREAD

**Issue by eturienzo** [ALIADA/aliada-tool#18]
Create a user log to show the differents items that have not the corresponding mandatory tags

**Comment by idoiamurua** [comment]
@eturienzo , @xmolero 
Can this issue be closed?

**Comment by xmolero** [comment]
No, we have to do the mandatory tags from Dublin Core.

**Comment by idoiamurua** [comment]
OK

**Comment by eturienzo** [comment]
The DC is validated
