### ISSUE TITLE
RDFizer output validation

### ISSUE THREAD

**Issue by idoiamurua** [ALIADA/aliada-tool#36]
The following validations must be carried out, according to D1.1 Requirements:

"The system shall provide some preconfigured SPARQL queries to check the generated
statements in the dataset to be published in the Linked Open Data cloud. Along with
a SPARQL end‐point to such dataset in order to executed the preconfigured queries.
The system shall check that the dataset contains at least 1000 triples."	

@scanbit @tpossemato Which type of queries are the most interesting?
E.g.: Give me all the authors
Give me all the manifestations
Give me the manifestations written by author X

**Comment by agazzarini** [comment]
@idoiamurua I'd need your opinion about the following doubts:

- what about the results of this validation? Do they have to block the execution?  
- Do they have to be stored somewhere (i.e. database)?

AG

**Comment by idoiamurua** [comment]
In my opinion, in the case there are errors, they should be shown to the end user and let him decide wether to go on with the process or stop it.

**Comment by agazzarini** [comment]
Ok, I could 

a) create another table that will report the validation report, for each conversion job
b) Update the job status to "ERROR". At the moment it only happens if there's a conversion error. In this case no "pure" conversion error happened but instead some sample record violates some validation constraint

What do you think?

**Comment by agazzarini** [comment]
In addition, @scanbit please keep in mind that there will be another web page where those errors have to be shown (in case the job is in error)

**Comment by idoiamurua** [comment]
I would save the validation errors in another table, because they are related to the rules files used by the RDFizer and should be checked by a tool expert to improve the tool. 
I understand that the other errors the RDFizer reports are related to other issues (connection, configuration, etc.)

**Comment by agazzarini** [comment]
Yes yes, I meant that: another table (something like "rdfizer_validation_results") that will hold only the validation errors.

**Comment by agazzarini** [comment]
I tried to use the Jena reasoner for validating the ontology together with a set of sample records. Bad news: if we want to use a rich inference model, we had to load the ontology completely (i.e. including the imported ontology)...and that leads to a perfect OOM: the ontology plus one (1) record need 2GB of RAM, a lot of CPU and takes a loooot of time :) 

I think things are not so different using another reasoner

**Comment by idoiamurua** [comment]
A pñossible solution could be to use a lighter version of Aliada ontology, with no instances, which it is much more smaller, and which it is enough to validate that the classes and properties generated are correct.
Where do you need to be placed? Must it be a graph in Virtuoso or an HTTP URI?

**Comment by agazzarini** [comment]
The Jena inference model allows to plug in a reasoner. That reason could an RDFS or an OWL compliant reasoner. The first one is very light but does few checks, while the OWL full compliant behaves as described in the previous post. There a middle way which represents a good compromise: OWLMicro and MiniReasoner. They seem to be faster. However, I have been only able to detect range and domain issues (about the statements). If, for example I put a wrong type (e.g. :xyz a efbfroo:blabalbla) it doesn't detect any error...maybe because it always assume as valid the AAA (Anyone can say Anything on Anything) principle. I have to investigate further but that could be logic: if you are using a class / property found in the ontology then it chekcs for domain and range validity, if you are using an unknown member it doesn't any check at all and assumes the statements as valid

**Comment by idoiamurua** [comment]
Hi Andrea,

I know what you mean because it has happened to me. I do not know  if you will find anything that detects those cases …

Here I send to you the lightest version of Aliada ontology (the rest of associated files, efrbroo.owl, time.owl, etc. are the same). It is very light, as it has no instances inside it. That I, it does not have triples of the type:



    <skos:Concept rdf:about="&Concept;IMAGE">
        <rdf:type rdf:resource="&owl;NamedIndividual"/>
        <rdfs:comment xml:lang="en">Europeana Media Type: IMAGE</rdfs:comment>
        <skos:prefLabel xml:lang="en">IMAGE</skos:prefLabel>
        <skosxl:literalForm xml:lang="en">IMAGE</skosxl:literalForm>
    </skos:Concept>

…….

How do you load the ontology  in the reasoned?

Best,
Idoia


De: Andrea Gazzarini [mailto:notifications@github.com]
Enviado el: viernes, 13 de febrero de 2015 9:39
Para: ALIADA/aliada-tool
CC: Murua Belacortu, Idoia
Asunto: Re: [aliada-tool] RDFizer output validation (#36)


The Jena inference model allows to plug in a reasoner. That reason could an RDFS or an OWL compliant reasoner. The first one is very light but does few checks, while the OWL full compliant behaves as described in the previous post. There a middle way which represents a good compromise: OWLMicro and MiniReasoner. They seem to be faster. However, I have been only able to detect range and domain issues (about the statements). If, for example I put a wrong type (e.g. :xyz a efbfroo:blabalbla) it doesn't detect any error...maybe because it always assume as valid the AAA (Anyone can say Anything on Anything) principle. I have to investigate further but that could be logic: if you are using a class / property found in the ontology then it chekcs for domain and range validity, if you are using an unknown member it doesn't any check at all and assumes the statements as valid

**Comment by agazzarini** [comment]
@idoiamurua I tried to inject Pellet Reasoner in Jena...and now I got this error:

Exception in thread "main" org.mindswap.pellet.exceptions.InconsistentOntologyException: Cannot do reasoning with inconsistent ontologies!
Reason for inconsistency: Individual http://aliada-project.eu/2014/aliada-ontology/id/resource/Concept/MFAB/Department/18 is forced to belong to class http://www.w3.org/2004/02/skos/core#Concept and its complement

Do you have an idea of its meaning? Why "is forced"?

**Comment by idoiamurua** [comment]
Try checking the consistency with Aliada ontology version that has no instances in it, or just with http://erlangen-crm.org/efrbroo/ ontology.

**Comment by agazzarini** [comment]
I already tried but it doesn't detect any error (with a sample record where I put some errors). Correct me if I'm wrong: I think that the only check that a reasoner could do are related with (probably there are some others)

- range check
- cardinality

Ex: if you declare 

:xyz a foaf:Persona  .  (note the typo, I wrote that in Italian)
:xyz foaf:name "Andrea" . 

This is perferctly valid because if :xyz has a foaf:name property, then that means it is a foaf:Person (and Persona which is an anknown class)

Another example using properties:

:xyz a foaf:Person . 
:xyz foaf:nome "Andrea" . 

This is also valid, the entity simply has an unknwon property. See below the exchange between a guy and one of the Sesame committer:

> "Is there a way to validate that the RDF triples that I generate (currently using Jena) are actually following the structure of my ontology?"

> this kind of validation is not part of the RDF model, and so most triplestores/APIs do not support it. I would recommend that you let go of this mindset, but to answer your question: yes, there are tools that allow you to do this kind of thing. One example is the Pellet OWL reasoner, which has a constraint validation mode

**Comment by idoiamurua** [comment]
And have you tried with the Pellet OWL reasoner, as the Sesame committer mentions?

**Comment by agazzarini** [comment]
Yes, it is not raising any issues if for example I use a wrong efrbroo 
predicate (e.g. efrbroo:F1_Worka)

The only check I have been able to detect is the range check (I put a 
literal instead of a reference)

**Comment by idoiamurua** [comment]
Can the resoner detectect that e.g.: the property <http://erlangen-crm.org/current/P102_has_title> is defined as:

<rdfs:domain rdf:resource="http://erlangen-crm.org/current/E71_Man-Made_Thing"/>
 <rdfs:range rdf:resource="http://erlangen-crm.org/current/E35_Title"/>

That is, when you generate a triple containing that predicate but with the range and/or domains not correct, e.g:
<Idoia> rdf:type <foaf:Person>
<Idoia> <http://erlangen-crm.org/current/P102_has_title> "Alex"

Would the reasoner throw an exception?

**Comment by agazzarini** [comment]
I was able to detect a range violation only putting a literal instead of an entity

**Comment by idoiamurua** [comment]
That is strange. How are you loading the ontology? 
It may not be including the following imports:
       
        <owl:imports rdf:resource="http://erlangen-crm.org/efrbroo/"/>
        <owl:imports rdf:resource="http://www.w3.org/2003/01/geo/wgs84_pos"/>
        <owl:imports rdf:resource="http://www.w3.org/2006/time"/>
        <owl:imports rdf:resource="http://www.w3.org/2008/05/skos-xl"/>
        <owl:imports rdf:resource="http://xmlns.com/foaf/0.1/"/> 

Are you using Jena framework? In that case, you may have to load those imported ontologies in the model one by one. Jena won´t load them. I think it ignores the import commands.

**Comment by agazzarini** [comment]
I already loaded the ontologies one by one...I know, that should be a 
stupid task but I don't see the light (yet)

**Comment by idoiamurua** [comment]
There is an example in Jena : http://jena.apache.org/documentation/inference/ (validation section):

     Model data = FileManager.get().loadModel(fname);
     InfModel infmodel = ModelFactory.createRDFSModel(data);
     ValidityReport validity = infmodel.validate();
     if (validity.isValid()) {
         System.out.println("OK");
     } else {
         System.out.println("Conflicts");
         for (Iterator i = validity.getReports(); i.hasNext(); ) {
             System.out.println(" - " + i.next());
         }
     }

The file "fname" should contain the tripels generated by the RDFizer and also the ontologies of ALIADA.
The Jena page says that it detects domain/range inconsistencies.

**Comment by agazzarini** [comment]
This doesn't detect anything :D

I was only able to detect a range error by using the OWLMicro / 
MiniReasoner

**Comment by idoiamurua** [comment]
And with the OWL reasoner? Try this:

     //Load Aliada ontology
     Model schema = RDFDataMgr.loadModel("file:data/aliada-ontology.owl") ;
     // Read into an existing Model rest of imported ontologies
     RDFDataMgr.read(schema, "http://erlangen-crm.org/efrbroo/") ;
     RDFDataMgr.read(schema, "http://www.w3.org/2003/01/geo/wgs84_pos") ;
     RDFDataMgr.read(schema, "http://www.w3.org/2006/time") ;
     RDFDataMgr.read(schema, "http://www.w3.org/2008/05/skos-xl") ;
     RDFDataMgr.read(schema, "http://xmlns.com/foaf/0.1/") ;
     
     //Load generated RDF
     Model data = RDFDataMgr.loadModel("file:data/generatedRDF.rdf") ;
     
     //Apply reasoner
     Reasoner reasoner = ReasonerRegistry.getOWLReasoner();
     reasoner = reasoner.bindSchema(schema);
     InfModel infmodel = ModelFactory.createInfModel(reasoner, data);
     
     //Check validity
     ValidityReport validity = infmodel.validate();
     if (validity.isValid()) {
         System.out.println("OK");
     } else {
         System.out.println("Conflicts");
         for (Iterator i = validity.getReports(); i.hasNext(); ) {
             ValidityReport.Report report = (ValidityReport.Report)i.next();
             System.out.println(" - " + report);
         }
     }

**Comment by agazzarini** [comment]
Maybe one day it will work...I executed these lines of code at 10:30 on 
my server (8CPU), it is still running and one CPU is praying me: "Kill me"

Note: as a test dataset, I loaded only 1 record

**Comment by idoiamurua** [comment]
Did you load "aliada-ontology.owl" from the file I sent to you the other day?
Or are you loading it from the URI http://aliada-project.eu/2014/aliada-ontology#?

**Comment by agazzarini** [comment]
Yes, i tried both. After two hours the process was still running 
My idea about this task is the following

- we cannot use an OWL reasoner to do that (at least OWL Mini or Micro)
- the RDF validation is a chimera. You can check only formal things like

1) Cardinality (which I don't see in our ontologies)
2) Disjunction and therefore unconsistent hierarchies (very hard to see this error)
3) usage of literals instead of entities (and viceversa) in triples

**Comment by agazzarini** [comment]
Guys, I surrender.  Things should be easy, very easy, following this link:

http://jena.apache.org/documentation/inference/#validation

But I'm not able to detect any issue, even range / domain or other stupid things.
This is the code I'm using:

*** invalid.nt ***
```
<http://www.szepmuveszeti.hu/id/resource/E19_Physical_Object/szepmuveszeti.hu_object_29> <http://www.w3.org/1999/02/22-rdf-syntax-ns#types> "szepmuveszeti.hu_object_29" .
<http://www.szepmuveszeti.hu/id/resource/E53_Place/1> <http://www.w3.org/2003/01/geo/wgs84_pos#lat> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> .
<http://www.artium.org/id/resource/F3_Manifestation_Product_Type/oooooo145395> <efrbroo:R40_has_representative_expression> "PippoPlutoEPaperino" .
```
And this is the code:

```
	public static void main(String[] args) {
		PelletOptions.USE_TRACING = true;
		Model schema = RDFDataMgr.loadModel("file:///work/workspaces/aliada/aliada-tool/aliada/aliada-rdfizer/src/test/resources/aliada-ontology.owl") ;
		RDFDataMgr.read(schema, "file:///work/workspaces/aliada/aliada-tool/aliada/aliada-rdfizer/src/test/resources/efrbroo.owl") ;
		RDFDataMgr.read(schema, "file:///work/workspaces/aliada/aliada-tool/aliada/aliada-rdfizer/src/test/resources/ecrm.owl") ;
		RDFDataMgr.read(schema, "http://www.w3.org/2003/01/geo/wgs84_pos");
		RDFDataMgr.read(schema, "http://www.w3.org/2006/time");
		RDFDataMgr.read(schema, "http://www.w3.org/2008/05/skos-xl");
		RDFDataMgr.read(schema, "http://xmlns.com/foaf/0.1/");
				 
		 //Load generated RDF
		 Model data = RDFDataMgr.loadModel("file:///work/workspaces/aliada/aliada-tool/aliada/aliada-rdfizer/src/test/resources/invalid.nt", Lang.NT) ;

		 InfModel infmodel = ModelFactory.createRDFSModel(schema, data);
		 ValidityReport validity = infmodel.validate();
		 if (validity.isValid()) {
		     System.out.println("OK");
		 } else {
		     System.out.println("Conflicts");
		     for (Iterator i = validity.getReports(); i.hasNext(); ) {
		         ValidityReport.Report report = (ValidityReport.Report)i.next();
		         System.out.println(" - " + report);
		     }
		 }		
	} 
```

**Comment by cgareta** [comment]
Hi, 

 

perhaps we could look for a similar innovative project that is working on technologies like that

 

Best, 

Cristina

 

De: Andrea Gazzarini [mailto:notifications@github.com] 
Enviado el: viernes, 20 de febrero de 2015 12:04
Para: ALIADA/aliada-tool
CC: cgareta
Asunto: Re: [aliada-tool] RDFizer output validation (#36)

 

Yes, i tried both. After two hours the process was still running 
My idea about this task is the following

*	we cannot use an OWL reasoner to do that (at least OWL Mini or Micro)
*	the RDF validation is a chimera. You can check only formal things like

1) Cardinality (which I don't see in our ontologies)
2) Disjunction and therefore unconsistent hierarchies (very hard to see this error)
3) usage of literals instead of entities (and viceversa) in triples

**Comment by agazzarini** [comment]
I think there's nothing innovative in such task....instead it is 
something that is not so "valid" according with the RDF data model.

Jena had a tool for doing something like that, called Eyeball, which 
seems no longer active.

**Comment by idoiamurua** [comment]
And if you ask for:

 if (validity.isClean()) {

instead of

 if (validity.isValid()) {

Does it alaso return "OK"?

**Comment by agazzarini** [comment]
Yes,
that is clean and valid :(

This Eyeball should be what we need, but it seems they removed this 
module, and also old versions are no longer downloadable

**Comment by idoiamurua** [comment]
And if you change the code specifying to use the RDFS_FULL reasoner:

```
	public static void main(String[] args) {
		PelletOptions.USE_TRACING = true;
		Model schema = RDFDataMgr.loadModel("file:///work/workspaces/aliada/aliada-tool/aliada/aliada-rdfizer/src/test/resources/aliada-ontology.owl") ;
		RDFDataMgr.read(schema, "file:///work/workspaces/aliada/aliada-tool/aliada/aliada-rdfizer/src/test/resources/efrbroo.owl") ;
		RDFDataMgr.read(schema, "file:///work/workspaces/aliada/aliada-tool/aliada/aliada-rdfizer/src/test/resources/ecrm.owl") ;
		RDFDataMgr.read(schema, "http://www.w3.org/2003/01/geo/wgs84_pos");
		RDFDataMgr.read(schema, "http://www.w3.org/2006/time");
		RDFDataMgr.read(schema, "http://www.w3.org/2008/05/skos-xl");
		RDFDataMgr.read(schema, "http://xmlns.com/foaf/0.1/");
				 
		 //Load generated RDF
		 Model data = RDFDataMgr.loadModel("file:///work/workspaces/aliada/aliada-tool/aliada/aliada-rdfizer/src/test/resources/invalid.nt", Lang.NT) ;

		 //Apply reasoner
		 Reasoner reasoner = ReasonerRegistry.getRDFSReasoner();
		 reasoner.setParameter(ReasonerVocabulary.PROPsetRDFSLevel,
                      ReasonerVocabulary.RDFS_FULL);
		 reasoner = reasoner.bindSchema(schema);
		 InfModel infmodel = ModelFactory.createInfModel(reasoner, data);
		 ValidityReport validity = infmodel.validate();
		 if (validity.isValid()) {
		     System.out.println("OK");
		 } else {
		     System.out.println("Conflicts");
		     for (Iterator i = validity.getReports(); i.hasNext(); ) {
		         ValidityReport.Report report = (ValidityReport.Report)i.next();
		         System.out.println(" - " + report);
		     }
		 }		
	} 
```

**Comment by agazzarini** [comment]
If I use RDFS_DEFAULT or SIMPLE then no check is done (i.e. valid and clean)
With RDFS_FULL the process is still running (started 40 mins ago)

Now, the question: how can we proceed with this task?

**Comment by idoiamurua** [comment]
I have used the OWLMicroReasoner and the following input invalid triples, and it gives me the following warning when asking if "isClean()":

...
     Conflicts
      - Warning ("range check"): "Literal value for object property (prop, value)"
     Culprit = http://www.szepmuveszeti.hu/id/resource/E19_Physical_Object/szepmuveszeti.hu_object_29
     Implicated node: http://erlangen-crm.org/current/P1_is_identified_by
     Implicated node: 'PippoPlutoEPaperino'
...

The input triples (the range of <http://erlangen-crm.org/current/P1_is_identified_by> is not an String, but <http://erlangen-crm.org/current/E41_Appellation>:

*** invalid.nt ***
```
<http://www.szepmuveszeti.hu/id/resource/E19_Physical_Object/szepmuveszeti.hu_object_29> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://erlangen-crm.org/current/E19_Physical_Object> .
<http://www.szepmuveszeti.hu/id/resource/E19_Physical_Object/szepmuveszeti.hu_object_29> <http://erlangen-crm.org/current/P1_is_identified_by> "PippoPlutoEPaperino" .
```

The code used:

	public static void main(String[] args) {
		PelletOptions.USE_TRACING = true;
		Model schema = RDFDataMgr.loadModel("file:///work/workspaces/aliada/aliada-tool/aliada/aliada-rdfizer/src/test/resources/aliada-ontology.owl") ;
		RDFDataMgr.read(schema, "file:///work/workspaces/aliada/aliada-tool/aliada/aliada-rdfizer/src/test/resources/efrbroo.owl") ;
		RDFDataMgr.read(schema, "file:///work/workspaces/aliada/aliada-tool/aliada/aliada-rdfizer/src/test/resources/ecrm.owl") ;
		RDFDataMgr.read(schema, "http://www.w3.org/2003/01/geo/wgs84_pos");
		RDFDataMgr.read(schema, "http://www.w3.org/2006/time");
		RDFDataMgr.read(schema, "http://www.w3.org/2008/05/skos-xl");
		RDFDataMgr.read(schema, "http://xmlns.com/foaf/0.1/");
				 
		 //Load generated RDF
		 Model data = RDFDataMgr.loadModel("file:///work/workspaces/aliada/aliada-tool/aliada/aliada-rdfizer/src/test/resources/invalid.nt", Lang.NT) ;

		 //Apply reasoner
		 Reasoner reasoner = ReasonerRegistry.getOWLMicroReasoner();
		 reasoner = reasoner.bindSchema(schema);
		 InfModel infmodel = ModelFactory.createInfModel(reasoner, data);
		 ValidityReport validity = infmodel.validate();
		 if (validity.isClean()) {
		     System.out.println("OK");
		 } else {
		     System.out.println("Conflicts");
		     for (Iterator i = validity.getReports(); i.hasNext(); ) {
		         ValidityReport.Report report = (ValidityReport.Report)i.next();
		         System.out.println(" - " + report);
		     }
		 }		
	} 
```

**Comment by agazzarini** [comment]
After how many hours? I have 8CPU and I'm running that process with 3GB 
of RAM...the process is still running and one CPU is at 100%

**Comment by idoiamurua** [comment]
No. Just seconds!

**Comment by agazzarini** [comment]
absurd...I copied and pasted your code :( Opening with JConsole, it 
seems the thread is blocked in bindSchema()

Stack trace:
java.util.ArrayList.indexOf(ArrayList.java:297)
java.util.ArrayList.contains(ArrayList.java:281)
com.hp.hpl.jena.reasoner.rulesys.impl.RETEEngine.addTriple(RETEEngine.java:364)
    - locked com.hp.hpl.jena.reasoner.rulesys.impl.RETEEngine@4771c0b8
com.hp.hpl.jena.reasoner.rulesys.impl.RETEEngine.fastInit(RETEEngine.java:146)
com.hp.hpl.jena.reasoner.rulesys.FBRuleInfGraph.prepare(FBRuleInfGraph.java:485)
    - locked com.hp.hpl.jena.reasoner.rulesys.FBRuleInfGraph@2af5e863
com.hp.hpl.jena.reasoner.rulesys.GenericRuleReasoner.bindSchema(GenericRuleReasoner.java:336)
com.hp.hpl.jena.reasoner.rulesys.FBRuleReasoner.bindSchema(FBRuleReasoner.java:215)
eu.aliada.rdfizer.Main.main(Main.java:48)

**Comment by idoiamurua** [comment]
Are you in debug mode? If I am in Debug mode it does never finish. If I just run it, it finishes in seconds.

**Comment by agazzarini** [comment]
the same...maybe has something to do with some native component...I'm on 
Linux

**Comment by idoiamurua** [comment]
I am in Windows.
I have something else different from you. I have just realised. I load all the *.owl files form the local file system:

		        Model schema = RDFDataMgr.loadModel("file:///D:/Proyectos/023779_ALIADA/Development/aliada-rdfizer/Ontology/aliada-ontology.owl") ;
		        RDFDataMgr.read(schema, "file:///D:/Proyectos/023779_ALIADA/Development/aliada-rdfizer/Ontology/efrbroo.owl") ;
		        RDFDataMgr.read(schema, "file:///D:/Proyectos/023779_ALIADA/Development/aliada-rdfizer/Ontology/current.owl") ;
		        RDFDataMgr.read(schema, "file:///D:/Proyectos/023779_ALIADA/Development/aliada-rdfizer/Ontology/wgs84_pos.owl");
		        RDFDataMgr.read(schema, "file:///D:/Proyectos/023779_ALIADA/Development/aliada-rdfizer/Ontology/time.owl");
		        RDFDataMgr.read(schema, "file:///D:/Proyectos/023779_ALIADA/Development/aliada-rdfizer/Ontology/skos-xl.owl");
		        RDFDataMgr.read(schema, "file:///D:/Proyectos/023779_ALIADA/Development/aliada-rdfizer/Ontology/0.1.owl");

**Comment by agazzarini** [comment]
I don't think this is the problem...the process hangs on 
reasoner.bindSchema(). Hoewever, i will try

**Comment by agazzarini** [comment]
g-o-i-n-g c-r-a-z-y!

**Comment by idoiamurua** [comment]
Are you using the OWLMicroReasoner and not debugging?

My whole code again. Just in case:

		        Model schema = RDFDataMgr.loadModel("file:///D:/Proyectos/023779_ALIADA/Development/aliada-rdfizer/Ontology/aliada-ontology.owl") ;
		        RDFDataMgr.read(schema, "file:///D:/Proyectos/023779_ALIADA/Development/aliada-rdfizer/Ontology/efrbroo.owl") ;
		        RDFDataMgr.read(schema, "file:///D:/Proyectos/023779_ALIADA/Development/aliada-rdfizer/Ontology/current.owl") ;
		        RDFDataMgr.read(schema, "file:///D:/Proyectos/023779_ALIADA/Development/aliada-rdfizer/Ontology/wgs84_pos.owl");
		        RDFDataMgr.read(schema, "file:///D:/Proyectos/023779_ALIADA/Development/aliada-rdfizer/Ontology/time.owl");
		        RDFDataMgr.read(schema, "file:///D:/Proyectos/023779_ALIADA/Development/aliada-rdfizer/Ontology/skos-xl.owl");
		        RDFDataMgr.read(schema, "file:///D:/Proyectos/023779_ALIADA/Development/aliada-rdfizer/Ontology/0.1.owl");

		         //Load generated RDF
		         Model data = RDFDataMgr.loadModel("file:///D:/Proyectos/023779_ALIADA/Development/aliada-rdfizer/Ontology/invalid.nt", Lang.NT) ;

		         //Apply reasoner
		         //Reasoner reasoner = ReasonerRegistry.getRDFSReasoner();
		         Reasoner reasoner = ReasonerRegistry.getOWLMicroReasoner();
		         //reasoner.setParameter(ReasonerVocabulary.PROPsetRDFSLevel,
		           //           ReasonerVocabulary.RDFS_FULL);
		         reasoner = reasoner.bindSchema(schema);
		         InfModel infmodel = ModelFactory.createInfModel(reasoner, data);
		         ValidityReport validity = infmodel.validate();
		         if (validity.isClean()) {
		             System.out.println("OK");
		         } else {
		             System.out.println("Conflicts");
		             for (Iterator i = validity.getReports(); i.hasNext(); ) {
		                 ValidityReport.Report report = (ValidityReport.Report)i.next();
		                 System.out.println(" - " + report);
		             }
		         }

**Comment by agazzarini** [comment]
Yes. I see that the problem is in RETEEngine which is looping infinitely

   for (Iterator<Triple> i = *inserts*.find(new TriplePattern(null, 
null, null)); i.hasNext(); ) {
       addTriple( i.next(), false );
   }

"inserts" is an empty graph so the loop never ends...

BTW: many thanks

**Comment by agazzarini** [comment]
A little step ahead...I was using a recent version of Jena (2.10.0) so I 
reverted the pom.xml and now I'm with 2.6.4. The process still never 
ends but the blocking point is on validate()

@Idoiamurua: what version of Jena are u using?

**Comment by idoiamurua** [comment]
I am using Jena 2.11.2, it seems it gets it from the maven repository. I cannot see it included in ALIADA global POM or in module LinksDiscovery POM (where I have coded this piece).

**Comment by agazzarini** [comment]
Update: using Java 8 I have the same your behaviour ;)

**Comment by idoiamurua** [comment]
Do you mean that it works in you computer?

**Comment by agazzarini** [comment]
Yes!

**Comment by agazzarini** [comment]
Task has been closed after merging the development branch associated with this issue. 
The Wiki section that describes the REST interface of the module, has been updated. therefore providing a description of the new information added on top of the getJob service.
