### ISSUE TITLE
Links Discovery: ad hoc code for some datasets

### ISSUE THREAD

**Issue by idoiamurua** [ALIADA/aliada-tool#37]
The following datasets do not provide an SPARQL endpoint, but an ad hoc API to do the searching of resources:

* Open Library: https://openlibrary.org/search?title=quijote&author=cervantes
* lobid: http://lobid.org/person?name=cervantes , http://lobid.org/organisation?name=cern , http://lobid.org/resource?name=quijote
* VIAF: http://viaf.org/viaf/search?query=cql.any+all+%22cervantes%22&sortKeys=holdingscount&recordSchema=BriefVIAF
* Library of Congress: Subject Headings: http://id.loc.gov/search/?q=fish&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fauthorities%2Fsubjects
* Library of Congress: MARC Codes List: http://id.loc.gov/search/?q=Spanish&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fvocabulary%2Flanguages
, http://id.loc.gov/search/?q=Asia&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fvocabulary%2FgeographicAreas , 
http://id.loc.gov/search/?q=Spain&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fvocabulary%2Fcountries

In these cases it is required to build an ad hoc code that makes use of those APIs to search for similar resources.
That is, SILK cannot be used.
This code will be developed for the second prototype.

**Comment by idoiamurua** [comment]
@agazzarini 

Could you give an example of the triples generated by the NLP component?
I need to know in which data property you store the Organisation/person name extracted. Is it in the ecrm:P3_has_note data property?
I will use that value to look for the corresponding Subject Heading in the Library of Congress.

**Comment by agazzarini** [comment]
I will follow your suggestion so if I remember well yes, it is in a 
P3:has_note data property (sorry it's not yet implemented)

**Comment by cgareta** [comment]
Hi @agazzarini and @idoiamurua

 

Regarding the MARC tags and NLP: the most relevant note tag to process is the abstract-summary tag (520), and that is related to Expression entity. So, if @idoiamurua has to select Work-Expression group or Manifestation-Item group to do the NLP, I would select the first one, the Work-Expression group:

 


NOTE TYPE

TAG

SUBFIELD

FRBR ENTITY

RELATIONSHIP

	

500 - General Note (R) Full | Concise

 

 

 

 

	

501 - With Note (R) Full | Concise

 

 

 

 

	

502 - Dissertation Note (R) Full | Concise

 

 

 

 

	

504 - Bibliography, etc. Note (R) Full | Concise

504

a

Work

Form of work

	

505 - Formatted Contents Note (R) Full | Concise

505

a

Expression

Summarization of content

	

506 - Restrictions on Access Note (R) Full | Concise

 

 

 

 

	

507 - Scale Note for Graphic Material (NR) Full | Concise

 

 

 

 

	

508 - Creation/Production Credits Note (R) Full | Concise

 

 

 

 

	

510 - Citation/References Note (R) Full | Concise

 

 

 

 

	

511 - Participant or Performer Note (R) Full | Concise

511

a

Manifestation

Statement of responsibility

	

513 - Type of Report and Period Covered Note (R) Full | Concise

 

 

 

 

	

514 - Data Quality Note (NR) Full | Concise

 

 

 

 

	

515 - Numbering Peculiarities Note (R) Full | Concise

 

 

 

 

	

516 - Type of Computer File or Data Note (R) Full | Concise

 

 

 

 

	

518 - Date/Time and Place of an Event Note (R) Full | Concise

 

 

 

 

	

520 - Summary, etc. (R) Full | Concise

520

a

Expression

Summarization of content

	

521 - Target Audience Note (R) Full | Concise

521

a

Work

Intended audience

	

522 - Geographic Coverage Note (R) Full | Concise

522

a

Place

Term for place

	

524 - Preferred Citation of Described Materials Note (R) Full | Concise

 

 

 

 

	

525 - Supplement Note (R) Full | Concise

 

 

 

 

	

526 - Study Program Information Note (R) Full | Concise

 

 

 

 

	

530 - Additional Physical Form available Note (R) Full | Concise

530

a

Manifestation

Alternate

	

533 - Reproduction Note (R) Full | Concise

 

 

 

 

	

534 - Original Version Note (R) Full | Concise

 

 

 

 

	

535 - Location of Originals/Duplicates Note (R) Full | Concise

 

 

 

 

	

536 - Funding Information Note (R) Full | Concise

 

 

 

 

	

538 - System Details Note (R) Full | Concise

 

 

 

 

	

540 - Terms Governing Use and Reproduction Note (R) Full | Concise

540

a

Manifestation

Access restrictions

	

541 - Immediate Source of Acquisition Note (R) Full | Concise

541

a

Item

Provenance

	

542 - Information Relating to Copyright Status (R) Full | Concise

 

 

 

 

	

544 - Location of Other Archival Materials Note (R) Full | Concise

 

 

 

 

	

545 - Biographical or Historical Data (R) Full | Concise

545

a

Person/Corp

Biography/history*

	

546 - Language Note (R) Full | Concise

546

a

Expression

Language of expression

	

 

 

 

De: Idoia [mailto:notifications@github.com] 
Enviado el: lunes, 09 de marzo de 2015 16:11
Para: ALIADA/aliada-tool
Asunto: Re: [aliada-tool] Links Discovery: ad hoc code for some datasets (#37)

 

@agazzarini <https://github.com/agazzarini>  

Could you give an example of the triples generated by the NLP component?
I need to know in which data property you store the Organisation/person name extracted. Is it in the ecrm:P3_has_note data property?
I will use that value to look for the corresponding Subject Heading in the Library of Congress.

**Comment by agazzarini** [comment]
Hi @idoiamurua finally I found the issue :) 

According with your suggestion I will produce these triples:
```
Darwin rdf:type skos:Concept 
PersonsCollection skos:member Darwin 
Work1 rdf:type ecrm:E89_PropositionalObject 
Work1 ecrm:P129_is_about Darwin
```

Now, I think that we should also say something like:

```
Darwin skos:prefLabel "Darwing" . 
```
What do you think?

**Comment by idoiamurua** [comment]
Yes. I agree!

**Comment by idoiamurua** [comment]
The code to link with the following datasets, with no SPARQL endpoint, has already been developed:

* Open Library: https://openlibrary.org/search?title=quijote&author=cervantes
* lobid: http://lobid.org/person?name=cervantes , http://lobid.org/organisation?name=cern , http://lobid.org/resource?name=quijote
* VIAF: http://viaf.org/viaf/search?query=cql.any+all+%22cervantes%22&sortKeys=holdingscount&recordSchema=BriefVIAF
* Library of Congress: Subject Headings: http://id.loc.gov/search/?q=fish&q=cs%3Ahttp%3A%2F%2Fid.loc.gov%2Fauthorities%2Fsubjects
