### ISSUE TITLE
RDF-izer: MARC authority conversion rules

### ISSUE THREAD

**Issue by agazzarini** [ALIADA/aliada-tool#75]
Once we get the mapping files, we need to create (on RDFizer side) the corresponding stuff for providing the appropriate conversion. That involves:

- execution pipeline (Apache Camel)
- conversion template (Apache Velocity)

**Comment by agazzarini** [comment]
Created (local at the moment) branch "l_auth_mapping"

**Comment by agazzarini** [comment]
@tpossemato although I'm starting now with this issue, I'd need some sample record for validating the conversion task

**Comment by agazzarini** [comment]
- Remote branch (r_auth_mapping) created
- Excel mapping file committed

**Comment by agazzarini** [comment]
@tpossemato  The first row in the mapping file says :    
```
E21 Person and F38 Character
```   
but F38_Character is not a valid EFRBROO Class, so what is the correct mapping?

**Comment by tpossemato** [comment]
In the first row I just reported the 'history' of class E21 Person, So, consider as corrct mapping the following:
Person = E21 Person

**Comment by tpossemato** [comment]
I have a doubt about this: E21_Person has as equivalent (in EFRBRoo) F10_Person (that I used in the following rows)... what's the difference between one and the other and what's the best to use in this case?

**Comment by agazzarini** [comment]
@idoiamurua any thoughts about this?

**Comment by idoiamurua** [comment]
In EFRBRoo ontology (which includes CIDOC-CRM) it says:
```
<rdf:Description rdf:about="&ecrm;E21_Person">
        <owl:equivalentClass rdf:resource="&efrbroo;F10_Person"/>
</rdf:Description>
```
That is, they are the same class. I do not why FRBRoo included F10_Person class, when the E21_Person class already existed in CIDOC. May be to explictly express that FRBRoo needs also a class to represent that kind of entity.

Summarising, you can use E21_Person.

**Comment by agazzarini** [comment]
@tpossemato There are some rows in the mapping file where unexisting entities have been used. 

377a, 372a: **F51 Pursuit** doesn't exist
368d: **F50 Controlled Access Point** doesn't exist
all rows associated with 500a: Refers to a class whose name starts with "F52" which doesn't exist
all rows associated with 100 3# Heading-Personal Name - Family Name: **F39_Family** doesn't exist

Could you please replace those classes or rewrite this rules?

**Comment by idoiamurua** [comment]
Instead of **F51 Pursuit** use the **ecrm:E7_Activity** more general class. **F51 Pursuit** class is included in the RDFS definition of the FRBRoo model in http://www.cidoc-crm.org/rdfs/FRBR2.0-draft-B.rdfs as:
```
<rdfs:Class rdf:about="F51_Pursuit">
<rdfs:label xml:lang="en">Pursuit</rdfs:label>
<rdfs:comment>
This class comprises periods of continuous activity of an Actor in a specific professional or creative domain or field.
</rdfs:comment>
<rdfs:subClassOf rdf:resource="E7_Activity"/>
</rdfs:Class>
```
But the class is not included in Erlangen FRBRoo OWL version.

The same applies for **F50 Controlled Access Point** class. Use **efrbroo:F13_Identifier** instead.
The same applies for **F52_Name_Use_Activity** class. Use **ecrm:E13_Attribute_Assignment** instead.
The same applies for **F39_Family** class. Use **ecrm:E74_Group** instead.

**Comment by agazzarini** [comment]
Ok, @idoiamurua. Thanks a lot!

2015-04-24 12:19 GMT+02:00 Idoia <notifications@github.com>:

**Comment by idoiamurua** [comment]
And use **ecrm:P140_assigned_attribute_to** property instead of **R63 named** property in 500a tag.

**Comment by agazzarini** [comment]
@tpossemato I have some questions about the 500 section. This is the first.

**Values of $i**  
As far as I understood, the value of the $i subfield qualifies the relationship; so the question is: what kind of values we can find within this subfield? Is it a free text? In the first mapping you say, for example, _pseudonymous_. Do I have to look for this specific value? What about if the term is in Spanish?

I had a look here [1] and here [2] and it seems that value could be everything. If it is so, could we map the 500$a with a general / generic rule?  

----------------------------------
[1] http://www.loc.gov/marc/authority/ad500.html     
[2] http://www.loc.gov/marc/authority/adtracing.html

**Comment by tpossemato** [comment]
Hi Andrea, the page to see how the $i can be produced in the Marc21 authority is the following:
http://www.loc.gov/marc/authority/adtracing.html, with particulary attention to 
$i - Relationship information
In the Marc21 authority format this field is a 'free text'... different is now in RDA, where the text is choosen from a list also published in Open Metadata Registry: see ofr example http://metadataregistry.org/schemaprop/list/schema_id/13.html

To answer to your last question, I need evaluate if we can mapping this with a generic "is related to".... a lot of meaning so will be lost... but I haven't other solution for this. Give me few minutes to evaluate this option.

**Comment by tpossemato** [comment]
Hi @agazzarini,
in the EFRBRoo I didn't find any properties that summarizes all this type of relationships between entities (such as a generic 'is related to'). I'm sorry, but I don't know how solve this task.

**Comment by agazzarini** [comment]
@idoiamurua any idea / suggestion? Briefly:  we have a tag which contains a kind of relation between the current resource and another. Since the relationship kind is expressed in the $i subfield in a unstructured way (it's a free text, could be everything), we cannot identify, as the mapping file reports, one mapping for each kind of relation.   

Instead, we could create a set of triples describing a general "relation", qualified with (shooting in the dark, here) an E55_Type which in turn has a note containing the relationship kind (e.g. pseudonymous)

Could you please help us?

**Comment by idoiamurua** [comment]
I think you refer to tag number 500? Do you refer to the following case?
![image](https://cloud.githubusercontent.com/assets/7601333/7385950/21efee6e-ee4e-11e4-937f-9cd315e7bd49.png)

@tpossemato Could you give us an example with values for that tag?
Otherwise, it is difficult to know how to map it.

**Comment by idoiamurua** [comment]
@tpossemato Could you give us examples of the following cases of tag "500":

500	a $i (has current member)
500	a $i (has former member)
500	a $i (is part of)
500	a $i (known as)

**Comment by tpossemato** [comment]
@idoiamurua I'm sending the file with the authority records you required via e-mail. Let me know if it's enough for you.

**Comment by idoiamurua** [comment]
OK

**Comment by tpossemato** [comment]
Hi Idoia, attached the file with authority records you required. Let me know if it's enough for you.

Best regards

Tiziana 

 

Da: Idoia [mailto:notifications@github.com] 
Inviato: lunedì 4 maggio 2015 12:36
A: ALIADA/aliada-tool
Cc: tpossemato
Oggetto: Re: [aliada-tool] RDF-izer: MARC authority conversion rules (#75)

 

@tpossemato <https://github.com/tpossemato>  Could you give us examples of the following cases of tag "500":

500 a $i (has current member)
500 a $i (has former member)
500 a $i (is part of)
500 a $i (known as)

**Comment by idoiamurua** [comment]
Could you send them in MARC XML? I do not know MARC and I cannot find where the 500 tag is. Sorry.

**Comment by idoiamurua** [comment]
Leave it Tizziana. I have checked the ".mrk" file and now I can see it more clearly.

**Comment by tpossemato** [comment]
Perfect. Let me know if it's clear and enough!

**Comment by idoiamurua** [comment]
=500  1\$(known as):$iKing, Stephen
Is this correct or should it be:

=500  1\$i(known as):$aKing, Stephen

**Comment by tpossemato** [comment]
The second is correct... 
=500 1\$i(known as):$aKing, Stephen 
(sorry!)

**Comment by idoiamurua** [comment]
I would do the mapping using the P3_has_note property, and placing as the property value the concatenation of $i and $a values, separated by a space character.

Here are some examples:

```
=500 1\$i(known as):$aKing, Stephen 
```
would be mapped to:
```
<#F1> rdf:type <efrbroo:F10_Person> .
<#F1> ecrm:P3_has_note "(known as): King, Stephen"
```
Another example:
```
=500  \0$i(has current member):$aGallagher, Liam
```
would be mapped to:
```
<#F2> rdf:type <efrbroo:F11_Corporate_Body> .
<#F2> ecrm:P3_has_note "(has current member): Gallagher, Liam"
```
Moreover, MARC says about 500 tag: "General notes are recorded in field 500 (General Note)".
