### ISSUE TITLE
FRBR (remaining) entities detection

### ISSUE THREAD

**Issue by agazzarini** [ALIADA/aliada-tool#78]
When we spoke the last time, @cgareta told me that for this last phase we should map all FRBR entities. So this issue is for putting the required logic to do that into the RDFizer

**Comment by emiliano-cammilletti** [comment]
@cgareta I need the configuration file for new entities detection. Thanks in advance

**Comment by cgareta** [comment]
I attach the first draft of the second part of the ALIADA mapping

 

Please, note that the Dublin core to RDF mapping is not finished

 

Best regards, 

Cristina

 

De: emiliano-cammilletti [mailto:notifications@github.com] 
Enviado el: lunes, 09 de febrero de 2015 15:25
Para: ALIADA/aliada-tool
CC: cgareta
Asunto: Re: [aliada-tool] FRBR (remaining) entities detection (#78)

 

@cgareta <https://github.com/cgareta>  I need the configuration file for new entities detection. Thanks in advance

**Comment by emiliano-cammilletti** [comment]
I implemented the detection for the new entities
