### ISSUE TITLE
DB tables new structure

### ISSUE THREAD

**Issue by idoiamurua** [ALIADA/aliada-tool#84]
The dataset of ARTIUM (or any other organization/institution with one or several collections) could be organized as follows:

- http://data.artium.org/id/collections/library/bib/F1_Work/XXXXXX
- http://data.artium.org/id/collections/library/aut/CLASSNAME/XXXXXX
- http://data.artium.org/id/collections/museum/paintings/E19_Physical_Object/YYYYY 
- http://data.artium.org/id/collections/museum/sculptures/E19_Physical_Object/YYYYY

To be able to do this we have to add/change some DB tables.

* One organization/institution -> It may contain several datasets
* One dataset:
     * It contains a field with the domain name, e.g.: data.artium.org 
     * It contains a field with the concept prefix, e.g.: collections or NULL
     * It contains a field with the dataset URI, that is, the URI of the HTML page describing the dataset. E.g.: http://data.artium.org , http://data.artium.org /id/collections, etc.  
     * It may contain several subsets.

* One subset:
     * It contains a field with the concept prefix, e.g.: library/bib,   museum/sculptures , etc. or NULL.
     * It contains a field with the subset URI, that is, the URI of the HTML page describing the subset. E.g.: http://data.artium.org /id/collections/museum/sculptures, etc.  
     * It contains a field with a graph URI where to store the triples. E.g.: http://data.artium.org /id/collections/museum/sculptures
     * It contains a field with a graph URI where to store the discovered links with external datasets. E.g.: http://data.artium.org /id/collections/museum/sculptures/links

According to this, the tables creation script would be:

        CREATE TABLE IF NOT EXISTS `aliada`.`organisation` (
            `organisationId` int(11) NOT NULL AUTO_INCREMENT,
            `organisation_name` varchar(32) NOT NULL,
            `organisation_path` varchar(128) NOT NULL,
            `organisation_logo` BLOB,
            `organisation_catalog_url` varchar(128) NOT NULL,
            `org_description`  VARCHAR( 245 ) default NULL,
            `org_home_page`  VARCHAR( 245 ) default NULL,
            `org_image_url`  VARCHAR( 245 ) default NULL,
            `aliada_ontology`  VARCHAR( 245 ) default NULL,
            `tmp_dir`  VARCHAR( 245 ) default NULL,
            `linking_client_app_bin_dir`  VARCHAR( 245 ) default NULL, 
            `linking_client_app_user`  VARCHAR( 245 ) default NULL, 
            `store_ip`  VARCHAR( 245 ) default NULL, 
            `store_sql_port`  INT default 1111, 
            `sql_login`  VARCHAR( 32 ) default NULL, 
            `sql_password`  VARCHAR( 32 ) default NULL, 
            `isql_command_path`  VARCHAR( 245 ) default NULL, 
            `isql_commands_file_global`  VARCHAR( 245 ) default NULL, 
            `isql_commands_file_subset_default`  VARCHAR( 245 ) default NULL, 
            `virtuoso_http_server_root`  VARCHAR( 245 ) default NULL,
            `ckan_api_url`  VARCHAR( 245 ) default NULL,
            `ckan_api_key`  VARCHAR( 245 ) default NULL,
            `ckan_org_url`  VARCHAR( 245 ) default NULL,
        PRIMARY KEY ( `organisationId` )
        ) ENGINE = InnoDB  DEFAULT CHARSET=utf8;

        CREATE TABLE IF NOT EXISTS `aliada`.`dataset` (
            `datasetId` int(11) NOT NULL AUTO_INCREMENT,
            `organisationId` int(11) NOT NULL,
            `dataset_desc`  VARCHAR( 245 ) default NULL,
            `domain_name` VARCHAR( 245 ) default NULL, 
            `uri_id_part` VARCHAR(10) NOT NULL,
            `uri_doc_part` VARCHAR(10) default NULL,
            `uri_def_art` VARCHAR(10) NOT NULL,
            `uri_concept_part` VARCHAR( 245 ) default NULL, 
            `uri_set_part` VARCHAR( 245 ) NOT NULL, 
            `listening_host` VARCHAR(45) default NULL,
            `virtual_host` VARCHAR(45) default NULL,
            `sparql_endpoint_uri`  VARCHAR( 245 ) default NULL, 
            `sparql_endpoint_login`  VARCHAR( 32 ) default NULL, 
            `sparql_endpoint_password`  VARCHAR( 32 ) default NULL, 
            `public_sparql_endpoint_uri`  VARCHAR( 245 ) default NULL,
            `dataset_author`  VARCHAR( 245 ) default NULL,
            `ckan_dataset_name`  VARCHAR( 245 ) default NULL,
            `dataset_long_desc`  VARCHAR( 800 ) default NULL,
            `dataset_source_url`  VARCHAR( 245 ) default NULL,
            `license_ckan_id`  VARCHAR( 245 ) default NULL,
            `license_url`  VARCHAR( 245 ) default NULL,
            `isql_commands_file_global`  VARCHAR( 245 ) default NULL, 
            `isql_commands_file_subset_default`  VARCHAR( 245 ) default NULL, 
       PRIMARY KEY ( `datasetId` ),
        FOREIGN KEY (`organisationId`) REFERENCES `aliada`.`organisation` (`organisationId`) ON DELETE CASCADE ON UPDATE CASCADE
        ) ENGINE = InnoDB  DEFAULT CHARSET=utf8;

        DROP TABLE `aliada`.`graph`;

        CREATE TABLE IF NOT EXISTS `aliada`.`subset` (
            `datasetId` int(11) NOT NULL,
            `subsetId` int(11) NOT NULL,
            `subset_desc`  VARCHAR( 245 ) default NULL,
            `uri_concept_part` VARCHAR( 245 ) default NULL, 
            `graph_uri`  VARCHAR( 245 ) default NULL, 
            `links_graph_uri`  VARCHAR( 245 ) default NULL, 
            `isql_commands_file_subset`  VARCHAR( 245 ) default NULL,
           FOREIGN KEY (datasetId) 
            REFERENCES dataset(datasetId) 
            ON DELETE CASCADE,
        PRIMARY KEY ( `datasetId`, `subsetId` )
        ) ENGINE = InnoDB  DEFAULT CHARSET=utf8;

Issues to consider:

* This new DB tables require an administration page to fill in the values.
* When the user logs in Aliada tool, it already has an organization/institution assigned. When he starts the conversion process, the user must select the dataset & subset where to load the generated triples.
* The field “namespace” in table `aliada`.`rdfizer_job_instances` is generated the following way:

       `aliada`.`rdfizer_job_instances`.`namespace` = “http://” + `aliada`.`dataset`.`domain_name`+ “/” + `aliada`.`dataset`.`uri_id_part` + “/” + `aliada`.`dataset`.`uri_concept_part` + “/” + `aliada`.`subset`.`uri_concept_part`

* When creating a subset, the corresponding two graphs must be created, and when the subset is removed, the corresponding two graps must be cleared too. 
     
     RDFStoreDAO.createGraphBySparql() <`aliada`.`subset`.`graph_uri`> and  <`aliada`.`subset`.`links_graph_uri`>
     RDFStoreDAO.removeGraphBySparql() <`aliada`.`subset`.`graph_uri`> and  <`aliada`.`subset`.`links_graph_uri`>

* When creating a new dataset (it will never be located in the default port of Virtuoso indicated in “virtuoso.ini” file, as it should be so that default page for the dataset works properly), the corresponding “create_new_dataset.sh” commands file must be executed from the ISQL of Virtuoso. 

* When creating an instance of `aliada`.`linksdiscovery_job_instances`, the field `input_graph` will have the value of `aliada`.`subset`.`graph_uri`, and the field `output_graph` will have the value of `aliada`.`subset`.`links_graph_uri` (the graph where the discovered links will be saved).

**Comment by idoiamurua** [comment]
Move subset.isql_commands_file to dataset.isql_commmands_file

**Comment by agazzarini** [comment]
Hi guys, 
be aware that as part of the issue #36 the database needs to be changed a bit. Specifically, the job_stats table has been changed (one additional column) and another table (for validation messages) has to be created.

**Comment by agazzarini** [comment]
The ddl scripts have been changed in the master branch.

**Comment by idoiamurua** [comment]
@xmolero Will you modify and create the new RDFizer table in aliada.scanbit.net machine?

May be the UI should show the new status fields values. Should't it Andrea?

**Comment by xmolero** [comment]
Yes, I do

**Comment by agazzarini** [comment]
Yes, sorry for delay in response. I updated the Wiki according with the new definition of the RDFizer tables (see the getJob service)

**Comment by agazzarini** [comment]
Did everybody / module commit the corresponding changes on the database? Because in case I think we can close the issue.

**Comment by idoiamurua** [comment]
Yes. We can close it.
