### ISSUE TITLE
UI: check field values in dataset table

### ISSUE THREAD

**Issue by idoiamurua** [ALIADA/aliada-tool#87]
@xmolero, @eturienzo  
When the end-user enters the values for the following fields, the UI module will check that they do not contain the "/" character inside them. These fields may only contain alphanumeric characters:

* dataset.uri_id_part
* dataset.uri_doc_part
* dataset.uri_def_part
* dataset.uri_set_part

The following fields may contain the "/" character inside them:

* dataset.uri_concept_part
* subset.uri_concept_part

The UI will also check that the following two fields cannot be the empty string at the same time. One of them must have a value:
* dataset.uri_doc_part
* dataset.uri_concept_part

**Comment by xmolero** [comment]
The UI check the values correctly.
