### ISSUE TITLE
RDFizer: Immutable Node approach is wrong

### ISSUE THREAD

**Issue by agazzarini** [ALIADA/aliada-tool#92]
@emiliano-cammilletti the ImmutableNode decorator approach doesn't work: The XPATH processor internally assign a handle to each node and it fails when trying to get the reference of the ImmutableNode (it doesn't have such handle).

So, coming back to the original plan: 

- we need a new method on Function that returns a string parameter escaped
- we need to replace all $node.getTextContent() or $node.textContent with $function.escape($node.textContent)

**Comment by emiliano-cammilletti** [comment]
I implemented the new function and I updated the files involved with the new function
