### ISSUE TITLE
RDFizer: Aliada ontology namespace ends with "#" instead of "/"

### ISSUE THREAD

**Issue by idoiamurua** [ALIADA/aliada-tool#96]
@agazzarini 

Hi Andrea,

I was reviewing the mapping files "*.vm" to check which new types must be created in Aliada ontology (e.g.: http://aliada-project.eu/2014/aliada-ontology#id/resource/Concept/ISMN) and I have realised that the RDFizer has been associating via the ecrm:P2_has_type property ALIADA types with the following URI:
``` 
http://aliada-project.eu/2014/aliada-ontology/id/resource/Concept/
``` 
instead of:
``` 
http://aliada-project.eu/2014/aliada-ontology#id/resource/Concept/
``` 
That is, the Aliada type instances have a "#" instead of a "/".

To solve this, I have been checking the code and I think that it is enough to carry out the following changes:

* Change in eu.aliada.rdfizer.rest.RDFizerResource.newJobFromStream():
``` 
instance.setAliadaOntologyNamespace("http://aliada-project.eu/2014/aliada-ontology/");
``` 
replace with:
``` 
instance.setAliadaOntologyNamespace("http://aliada-project.eu/2014/aliada-ontology#");
``` 
* Change in eu.aliada.rdfizer.datasource.Cache.adjustPrefixes():
``` 
		if (!prefix.endsWith("/")) {
			instance.setAliadaOntologyNamespace(prefix + "/");
		}
``` 
replace with:
``` 
		if (!prefix.endsWith("#")) {
			instance.setAliadaOntologyNamespace(prefix + "#");
		}
``` 

Am I right or am I missing something?

**Comment by agazzarini** [comment]
Yes that's right: that value is read from the database so putting a # at 
the end of the "aliada_ontology" column value should be enough. That 
piece of code just ensure that the URL is ending with #. So ok, the 
answer is yes

**Comment by idoiamurua** [comment]
And another place I see another thing to be changed related with this issue is in "marcxml.frbr.n3.vm" file. The following pieces of code:

```
#aliadaconcept('Concept/MARC/1')
#aliadaconcept('Concept/MARC/3')
#aliadaconcept('Concept/MARC/4')
#aliadaconcept('Concept/MARC/5')
#aliadaconcept('Concept/MARC/6')
```

should be:
```
#aliadaconcept('MARC/1')
#aliadaconcept('MARC/3')
#aliadaconcept('MARC/4')
#aliadaconcept('MARC/5')
#aliadaconcept('MARC/6')
```

because the "aliadaconcept" macro already adds the "concept/" string.

**Comment by agazzarini** [comment]
Right, could you please open an issue or change & commit?

**Comment by idoiamurua** [comment]
The issue is opened.
Ok, I will change the things commented in this issue.

Regarding the new types defined in ALIADA ontology, I have checked them all gain and I have seen that some of them have the "#" symbol and another ones the "/" :-(
I will ask Marta to change the ontology and rename the instances so that all of them follow the same pattern.

**Comment by agazzarini** [comment]
Ok

**Comment by idoiamurua** [comment]
@agazzarini 
Another question regarding the types:

If you place the following URL in a Web browser:

http://aliada.scanbit.net:8891/id/collections/library/bib/E36_Visual_Item/11604 

you will see that the generated type (P2_has_type) is:
http://aliada-project.eu/2014/aliada-ontology#/id/resource/Concept/ndigitalimagen

Why/Where does the RDFizer code add the "n" character in the beginning and end of "digitalimage" string?

The triple is generated in the following mapping sentence of "lido.n3.vm" file:

```
$resource_id_s $P2_has_type #aliada($function.escape($resourceType.textContent)) . 
```

and the record part it is applied on is:
```
         <lido:resourceType>
            <lido:term>digital image</lido:term>
          </lido:resourceType>

```

Any clue?

**Comment by idoiamurua** [comment]
I have just solved this last problem regarding the `<lido:resource>` tag mapping.

The solution has been to replace the following line in `lido.n3.vm` file:
```
#set($resourceType = $xpath.one("resourceType", $resource))
```

by:
```
#set($resourceType = $xpath.one("resourceType/term", $resource))
```

**Comment by agazzarini** [comment]
Great! Sorry, I overlooked your message

**Comment by agazzarini** [comment]
Idoia can we close this issue? Sorry I'm a bit lost ;)

**Comment by idoiamurua** [comment]
I am waiting till Marta changes the instances in Aliada ontology, otherwise I/we forget about it.

**Comment by agazzarini** [comment]
Ok, BTW I agree with you with the uniform naming we should have in our URI (# or /)

**Comment by idoiamurua** [comment]
Aliada ontology changed in Virtuoso.
