### ISSUE TITLE
RDFizer: VM_global_library.vm file bug

### ISSUE THREAD

**Issue by idoiamurua** [ALIADA/aliada-tool#99]
@agazzarini 

I have come across this line in the edn of "VM_global_librray.vm" file:

```
			$main_subject #ecrm('P137_exemplifies Darwin') $ne_s .
```

I think the "Darwin" string has come here with a copy/paste.

**Comment by agazzarini** [comment]
Yes I think,
@ecammilletti what is this?

**Comment by idoiamurua** [comment]
I think it is related to the NLP process, the named entities detection part.

**Comment by agazzarini** [comment]
Ahhhh ok, so Darwin has been "integrated" in the EFRBROO ontology....I 
will propose that change :)

**Comment by idoiamurua** [comment]
:-)

**Comment by idoiamurua** [comment]
May I do this correction?

**Comment by agazzarini** [comment]
Yes of course. Many thanks

**Comment by idoiamurua** [comment]
Bugs corrected.
